const language = {
  en: {
    "Gallery.title": "Pictures gallery",
    "Footer.copyright": "All right reserved.",
    "Header.headerTitle": "Nationales North West 2020",
    "Header.headerTitleShort": "Nationales N-W 2020",
    "Menu.home": "Home",
    "Menu.eventSprint": "Sprint",
    "Menu.eventMD": "Middle Distance",
    "Menu.eventLD": "Long Distance",
    "Menu.registration": "Entries",
    "Menu.startList": "Start list",
    "Menu.results": "Results",
    "Menu.gallery": "Pictures gallery",
    "Menu.accommodation": "Accomodation",
    "Menu.partners": "Partners",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph": "If you have any question, please contact the person below:",
    "SprintEvent.title": "Sprint",
    "MDEvent.title": "Middle Distance",
    "LDEvent.title": "Long Distance",
    "Accomodation.title": "Accomodation",
    "Accomodation.paragraph": "For all the accomodation you can check tourism office web sites of Fontainebleau, Melun and Nemours",
    "Accomodation.officeFontaineblau": "Tourism office of Fontainebleau",
    "Accomodation.officeMelun": "Tourism office of Melun",
    "Accomodation.officeNemours": "Tourism office of Nemours",
    "Home.title": "Home",
    "Home.bacgroundParagraph": "3 orienteering days in the forest of Fontainebleau and its surroundings",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21st",
    "Home.baliseSpParagraph2": "august",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22nd",
    "Home.baliseMdParagraph2": "august",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23rd",
    "Home.baliseLdParagraph2": "august",
    "Home.box1Title": "Informations",
    "Home.box11Paragraph": "Translation coming soon",
    "Home.box121Paragraph": "",
    "Home.box122Paragraph": "",
    "Home.box123Paragraph": "",
    "Home.box13Paragraph": "",
    "Home.box14Paragraph": "",
    "Home.box2Title": "Forbidden area",
    "Home.box2Paragraph": "The forbidden area are the ones inside the red border",
    "Home.box3Title": "Official book",
    "Home.box3Paragraph": "awailable soon",
    "Home.box5Title": "Map extracts",
    "Home.box5Paragraph": "awailable soon",
    "Home.box6Title": "Terrain Pictures",
    "Home.box6Paragraph": "More pictures",
    "Registration.title": "Entries",
    "Registration.paragraph": "The entries will take place on the website of the federation",
    "StartList.title": "Start list",
    "StartList.spTitle": "Sprint start list",
    "StartList.spParagraph": "not yet awailable",
    "StartList.mdTitle": "Middle distance start list",
    "StartList.mdParagraph": "not yet awailable",
    "StartList.ldTitle": "Long distance start list",
    "StartList.ldParagraph": "not yet awailable",
    "Partners.title": "Partners",
    "Partners.idf": "Île de France region",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Results",
    "Results.spTitle": "Sprint results",
    "Results.spParagraph": "not yet awailable",
    "Results.mdTitle": "Middle distance results",
    "Results.mdParagraph": "not yet awailable",
    "Results.ldTitle": "Long distance results",
    "Results.ldParagraph": "not yet awailable"
  },
  fr: {
    "Gallery.title": "Galerie photos",
    "Footer.copyright": "Tous droits réservés.",
    "Header.headerTitle": "Nationales Nord Ouest 2020",
    "Header.headerTitleShort": "Nationales N-O 2020",
    "Menu.home": "Accueil",
    "Menu.eventSprint": "Sprint",
    "Menu.eventMD": "Moyenne Distance",
    "Menu.eventLD": "Longue Distance",
    "Menu.registration": "Inscriptions",
    "Menu.startList": "Listes de départ",
    "Menu.results": "Résultats",
    "Menu.gallery": "Galerie photos",
    "Menu.accommodation": "Hébergements",
    "Menu.partners": "Partenaires",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph": "Pour toutes questions sur la Nationale Nord Ouest 2020 vous pouvez nous joindre à ces différents contacts",
    "SprintEvent.title": "Sprint",
    "MDEvent.title": "Moyenne Distance",
    "LDEvent.title": "Longue Distance",
    "Accomodation.title": "Hébergements",
    "Accomodation.paragraph": "Pour les hébergements vous pouvez consultez les sites des offices de tourisme de Fontainebleau, Melun et Nemours",
    "Accomodation.officeFontaineblau": "Office de tourisme de Fontainebleau",
    "Accomodation.officeMelun": "Office de tourisme de Melun",
    "Accomodation.officeNemours": "Office de tourisme de Nemours",
    "Home.title": "Accueil",
    "Home.bacgroundParagraph": "3 jours de course d'orientation en forêt de Fontainebleau et ses environs",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21",
    "Home.baliseSpParagraph2": "août",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22",
    "Home.baliseMdParagraph2": "août",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23",
    "Home.baliseLdParagraph2": "août",
    "Home.box1Title": "Informations",
    "Home.box11Paragraph": "La Nationale Nord Ouest 2020 de course d’orientation aura lieu du 21 au 23 août dans la forêt de Fontainebleau. Ce long week-end regroupe trois courses contant pour le classement national:",
    "Home.box121Paragraph": "- Un Sprint Urbain le vendredi 21 août après midi",
    "Home.box122Paragraph": "- Une Moyenne Distance le samedi 22 août après midi",
    "Home.box123Paragraph": "- Une Longue Distance le dimache 23 août matin",
    "Home.box13Paragraph": "Le terrain du sprint urbain est un petit village typique du sud de la Seine et Marne avec quelques petites ruelles ainsi que des quartiers residentiels offrants une vitesse de course plus élevé. La carte possède également plusieurs parcs ou prés qui necessiteront aux coureurs de s’adapter aux different environements.",
    "Home.box14Paragraph": "Les terrains de la moyenne distance et de la longue distance sont similaires et typiques de la forêt de fontainebleau. La carte possède de nombreux chaos rocheux qui rendent l’orientation difficile, le plus souvent sur les flans des nombreuses collines sableuses de la forêt de fontainebleau. Entre ces zones détaillés, la visibilité est bien meilleure et un réseau de chemin assez dense devrai permettre une navigation plus aisée.",
    "Home.box2Title": "Zones gelée",
    "Home.box2Paragraph": "Les zones gelée sont celles à l'intérieur de la ligne rouge",
    "Home.box3Title": "Livret d'accueil",
    "Home.box3Paragraph": "bientôt disponible",
    "Home.box5Title": "Extraits de cartes",
    "Home.box5Paragraph": "bientôt disponible",
    "Home.box6Title": "Photos du terrain",
    "Home.box6Paragraph": "Plus de photos",
    "Registration.title": "Inscriptions",
    "Registration.paragraph": "Les inscriptions vont être réalisées par le biais du site de la",
    "StartList.title": "Listes de départ",
    "StartList.spTitle": "Liste de départ du Sprint",
    "StartList.spParagraph": "Pas encore disponible",
    "StartList.mdTitle": "Liste de départ de la MD",
    "StartList.mdParagraph": "Pas encore disponible",
    "StartList.ldTitle": "Liste de départ de la LD",
    "StartList.ldParagraph": "Pas encore disponible",
    "Partners.title": "Partenaires",
    "Partners.idf": "Région Île de France",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Résultats",
    "Results.spTitle": "Résultats du Sprint",
    "Results.spParagraph": "Pas encore disponible",
    "Results.mdTitle": "Résultats de la MD",
    "Results.mdParagraph": "Pas encore disponible",
    "Results.ldTitle": "Résultats de la LD",
    "Results.ldParagraph": "Pas encore disponible"
  }
};

export default language;
