import lastUpate from "./lastUpdate";

const language = {
  en: {
    "Partners.lastUpate": `Last update : ${lastUpate.PARTNERS}`,
    "Results.lastUpate": `Last update : ${lastUpate.RESULTS}`,
    "StartList.lastUpate": `Last update : ${lastUpate.STARTLIST}`,
    "Training.lastUpate": `Last update : ${lastUpate.TRAINING}`,
    "SprintEvent.lastUpate": `Last update : ${lastUpate.SPRINTEVENT}`,
    "MDEvent.lastUpate": `Last update : ${lastUpate.MDEVENT}`,
    "LDEvent.lastUpate": `Last update : ${lastUpate.LDEVENT}`,
    "Accomodation.lastUpate": `Last update : ${lastUpate.ACCOMODATION}`,
    "Gallery.lastUpate": `Last update : ${lastUpate.GALLERY}`,
    "Contact.lastUpate": `Last update : ${lastUpate.CONTACT}`,
    "Home.lastUpate": `Last update : ${lastUpate.HOME}`,
    "LandingPage.Title": "Important information",
    "LandingPage.paragraph1":
      "The races planned from 21st to 23rd August are up to now maintained awaiting for the last new government instructions around June 20th. The teams are mobilized so that everything goes well. Registration will be open at the end of June. We hope to see many of you in August at Fontainebleau. See you soon.",
    "LandingPage.paragraph2": "Event director",
    "LandingPage.button": "Go to website",
    "Gallery.title": "Pictures gallery",
    "Gallery.urban": "Urban Sprint",
    "Gallery.forest": "Forest Race",
    "Footer.copyright": "All right reserved.",
    "Header.headerTitle": "Nationales North West 2020",
    "Header.headerTitleShort": "Nationales N-W 2020",
    "Menu.home": "Home",
    "Menu.eventTraining": "Training",
    "Menu.eventSprint": "Sprint",
    "Menu.eventMD": "Middle Distance",
    "Menu.eventLD": "Long Distance",
    "Menu.registration": "Entries",
    "Menu.startList": "Start list",
    "Menu.results": "Results",
    "Menu.gallery": "Pictures gallery",
    "Menu.accommodation": "Accomodation",
    "Menu.partners": "Partners",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph":
      "If you have any question, please adress it to the mail below:",
    "Training.bacgroundParagraph1": "Trainings",
    "Training.bacgroundParagraph2": "19-20 august 2020",
    "Training.title": "Trainings",
    "Training.box0Title1": "Informations",
    "Training.box01Paragraph1":
      "Balise 77 and OPA Montigny clubs welcome you to two training days the wednesday 19th and thursday 20th august 2020 from 13:00 to 18:00",
    "Training.box01Paragraph2":
      "A control network of 30 controls of black to green difficulty with small controls will be on Larchant's map and Bourron Marlotte's map. You will be able to get the map at Ermitage of Franchard (arena of the LD/MD) on wednesday and thurdays during opening hour.",
    "Training.box0Title2": "Prices",
    "Training.box02Paragraph1":
      'The price for one training is 4 euros. You can pay by transfer, IBAN : FR76 1010 7003 2700 1190 4923 683 BIC : BREDFRPPXXX or send a check to CDCO77 at the folowing addres Celine Dalier 26 Hameau de Bessonville 77760 La Chapelle La Reine, you must add the reference "Entrainements".',
    "Training.box01Paragraph3":
      "You can reserve you maps before the 7th august , here is the",
    "Training.box01Paragraph4": "link",
    "Training.training1Title": "Training 1",
    "Training.training1Box1Title": "Practical informations",
    "Training.training1Box1DateTitle": "Date: ",
    "Training.training1Box1DateParagraph": "19-20 august 2020",
    "Training.training1Box1PlacesTitle": "Place: ",
    "Training.training1Box1PlacesParagraph": "Forest of Fontainebleau",
    "Training.training1Box1MapTitle": "Map: ",
    "Training.training1Box1MapParagraph": "Larchant",
    "Training.training1Box1PlanTitle": "Plan: ",
    "Training.training1Box1PlanParagraph1": "Parking: ",
    "Training.training1Box1PlanParagraph2": "google link",
    "Training.training1Box4Title": "Map extracts",
    "Training.training1Box4Paragraph": "available soon",
    "Training.training2Title": "Training 2",
    "Training.training2Box1Title": "Practical informations",
    "Training.training2Box1DateTitle": "Date: ",
    "Training.training2Box1DateParagraph": "19-20 august 2020",
    "Training.training2Box1PlacesTitle": "Place: ",
    "Training.training2Box1PlacesParagraph": "Forest of Fontainebleau",
    "Training.training2Box1MapTitle": "Map: ",
    "Training.training2Box1MapParagraph": "Grotte Beatrix",
    "Training.training2Box1PlanTitle": "Plan: ",
    "Training.training1Box2PlanParagraph1": "Parking: ",
    "Training.training1Box2PlanParagraph2": 'Along "Grande Valée" road',
    "Training.training2Box4Title": "Map extracts",
    "Training.training2Box4Paragraph": "available soon",
    "SprintEvent.bacgroundParagraph": "Urban Sprint 21 august 2020",
    "SprintEvent.title": "Sprint",
    "SprintEvent.box1Title": "Practical informations",
    "SprintEvent.box1DateTitle": "Date: ",
    "SprintEvent.box1DateParagraph": "21 august 2020",
    "SprintEvent.box1StartListTitle": "Start list: ",
    "SprintEvent.box1StartListParagraph": "soon available",
    "SprintEvent.box1ResultTitle": "Result: ",
    "SprintEvent.box1ResultParagraph": "not yet available",
    "SprintEvent.box1ParkHomeDistanceTitle": "Park-arena distance: ",
    "SprintEvent.box1ParkHomeDistanceParagraph":
      "from 100 meters to 500 meters",
    "SprintEvent.box1HomeStartDistanceTitle": "Arena-start distance: ",
    "SprintEvent.box1HomeStartDistanceParagraph": "800 meters",
    "SprintEvent.box1OfficialBookTitle": "Official book: ",
    "SprintEvent.box1OfficialBookParagraph": "soon available",
    "SprintEvent.box1RaceAnnouncementTitle": "Invitation: ",
    "SprintEvent.box1RaceAnnouncementParagraph": "Download here",
    "SprintEvent.box1TrackDirectorTitle": "Event director: ",
    "SprintEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "SprintEvent.box1PlacesTitle": "Place: ",
    "SprintEvent.box1PlacesParagraph": "Chateau Landon",
    "SprintEvent.box1MapTitle": "Map: ",
    "SprintEvent.box1MapParagraph": "Chateau Landon",
    "SprintEvent.box1PlanTitle": "Plan: ",
    "SprintEvent.box1PlanParagraph": "soon available",
    "SprintEvent.box1Paragraph": "available soon",
    "SprintEvent.box2TrackTitle": "Courses",
    "SprintEvent.box2Track1": "A",
    "SprintEvent.box2Track2": "B",
    "SprintEvent.box2Track3": "C",
    "SprintEvent.box2CategoriesTitle": "Classes",
    "SprintEvent.box2Categories1": "to be defined",
    "SprintEvent.box2Categories2": "to be defined",
    "SprintEvent.box2Categories3": "to be defined",
    "SprintEvent.box2DistanceTitle": "Length (km)",
    "SprintEvent.box2Distance1": "to be defined",
    "SprintEvent.box2Distance2": "to be defined",
    "SprintEvent.box2Distance3": "to be defined",
    "SprintEvent.box2HeightDifferenceTitle": "Climb (m)",
    "SprintEvent.box2HeightDifference1": "to be defined",
    "SprintEvent.box2HeightDifference2": "to be defined",
    "SprintEvent.box2HeightDifference3": "to be defined",
    "SprintEvent.box2ControlTitle": "Controls",
    "SprintEvent.box2Control1": "to be defined",
    "SprintEvent.box2Control2": "to be defined",
    "SprintEvent.box2Control3": "to be defined",
    "SprintEvent.box2WinningTimeTitle": "Winning time",
    "SprintEvent.box2WinningTime1": "to be defined",
    "SprintEvent.box2WinningTime2": "to be defined",
    "SprintEvent.box2WinningTime3": "to be defined",
    "SprintEvent.box2Title": "Track details",
    "SprintEvent.box2Paragraph": "available soon",
    "SprintEvent.box3Title": "Prices",
    "SprintEvent.box3Paragraph11": "FFCO subscribers : ",
    "SprintEvent.box3Paragraph12":
      "18 years old and less : 5.00€, 18 years old and more : 6.00€",
    "SprintEvent.box3Paragraph21": "non-FFCO subscribers : ",
    "SprintEvent.box3Paragraph22":
      "Competition pass : 12.00€ ,discovery pass : 8.00€, family pass : 12.00€",
    "SprintEvent.box3Paragraph31": "SI rental : ",
    "SprintEvent.box3Paragraph32": "3€",
    "SprintEvent.box4Title": "Map extracts",
    "SprintEvent.box4Paragraph1": "available soon",
    "MDEvent.bacgroundParagraph": "Middle distance 22 august 2020",
    "MDEvent.title": "Middle Distance",
    "MDEvent.box1Title": "Practical informations",
    "MDEvent.box1DateTitle": "Date: ",
    "MDEvent.box1DateParagraph": "23 august 2020",
    "MDEvent.box1StartListTitle": "Start list: ",
    "MDEvent.box1StartListParagraph": "soon available",
    "MDEvent.box1ResultTitle": "Result: ",
    "MDEvent.box1ResultParagraph": "not yet available",
    "MDEvent.box1ParkHomeDistanceTitle": "Park-arena distance: ",
    "MDEvent.box1ParkHomeDistanceParagraph": "from 200 meters to 1000 meters ",
    "MDEvent.box1HomeStartDistanceTitle": "Arena-start distance: ",
    "MDEvent.box1HomeStartDistanceParagraph": "600 meters",
    "MDEvent.box1OfficialBookTitle": "official book: ",
    "MDEvent.box1OfficialBookParagraph": "soon available",
    "MDEvent.box1RaceAnnouncementTitle": "Invitation: ",
    "MDEvent.box1RaceAnnouncementParagraph": "Download here",
    "MDEvent.box1TrackDirectorTitle": "Event director: ",
    "MDEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "MDEvent.box1PlacesTitle": "Place: ",
    "MDEvent.box1PlacesParagraph": "Forest of Fontainebleau",
    "MDEvent.box1MapTitle": "Map: ",
    "MDEvent.box1MapParagraph": "Salamandre",
    "MDEvent.box1PlanTitle": "Plan: ",
    "MDEvent.box1PlanParagraph": "soon available",
    "MDEvent.box1Paragraph": "available soon",
    "MDEvent.box2TrackTitle": "Courses",
    "MDEvent.box2Track1": "A",
    "MDEvent.box2Track2": "B",
    "MDEvent.box2Track3": "C",
    "MDEvent.box2CategoriesTitle": "Classes",
    "MDEvent.box2Categories1": "to be defined",
    "MDEvent.box2Categories2": "to be defined",
    "MDEvent.box2Categories3": "to be defined",
    "MDEvent.box2DistanceTitle": "Length (km)",
    "MDEvent.box2Distance1": "to be defined",
    "MDEvent.box2Distance2": "to be defined",
    "MDEvent.box2Distance3": "to be defined",
    "MDEvent.box2HeightDifferenceTitle": "Climb (m)",
    "MDEvent.box2HeightDifference1": "to be defined",
    "MDEvent.box2HeightDifference2": "to be defined",
    "MDEvent.box2HeightDifference3": "to be defined",
    "MDEvent.box2ControlTitle": "Controls",
    "MDEvent.box2Control1": "to be defined",
    "MDEvent.box2Control2": "to be defined",
    "MDEvent.box2Control3": "to be defined",
    "MDEvent.box2WinningTimeTitle": "Winning time",
    "MDEvent.box2WinningTime1": "to be defined",
    "MDEvent.box2WinningTime2": "to be defined",
    "MDEvent.box2WinningTime3": "to be defined",
    "MDEvent.box2Title": "Track details",
    "MDEvent.box2Paragraph": "available soon",
    "MDEvent.box3Title": "Prices",
    "MDEvent.box3Paragraph11": "FFCO subscribers : ",
    "MDEvent.box3Paragraph12":
      "14 years old and less : 6.97€, 15-18 years old : 10.21€, 18 years old and more : 13.41€",
    "MDEvent.box3Paragraph21": "non-FFCO subscribers : ",
    "MDEvent.box3Paragraph22":
      "Competition pass : 15.00€ ,discovery pass : 12.00€, family pass : 15.00€",
    "MDEvent.box3Paragraph31": "SI rental : ",
    "MDEvent.box3Paragraph32": "3€",
    "MDEvent.box4Title": "Map extracts",
    "MDEvent.box4Paragraph1": "soon available",
    "LDEvent.bacgroundParagraph": " Long  distance 23 august 2020",
    "LDEvent.title": "Long Distance",
    "LDEvent.box1Title": "Practical informations",
    "LDEvent.box1DateTitle": "Date: ",
    "LDEvent.box1DateParagraph": "23 august 2020",
    "LDEvent.box1StartListTitle": "Start list: ",
    "LDEvent.box1StartListParagraph": "soon available",
    "LDEvent.box1ResultTitle": "Result: ",
    "LDEvent.box1ResultParagraph": "not yet available",
    "LDEvent.box1ParkHomeDistanceTitle": "Park-arena distance: ",
    "LDEvent.box1ParkHomeDistanceParagraph": "from 200 meters to 1000 meters ",
    "LDEvent.box1HomeStartDistanceTitle": "Arena-start distance: ",
    "LDEvent.box1HomeStartDistanceParagraph": "500 meters",
    "LDEvent.box1OfficialBookTitle": "Official book: ",
    "LDEvent.box1OfficialBookParagraph": "soon available",
    "LDEvent.box1RaceAnnouncementTitle": "Invitation: ",
    "LDEvent.box1RaceAnnouncementParagraph": "Download here",
    "LDEvent.box1TrackDirectorTitle": "Event director: ",
    "LDEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "LDEvent.box1PlacesTitle": "Place: ",
    "LDEvent.box1PlacesParagraph": "Forest of Fontainebleau",
    "LDEvent.box1MapTitle": "Map: ",
    "LDEvent.box1MapParagraph": "Franchard",
    "LDEvent.box1PlanTitle": "Plan: ",
    "LDEvent.box1PlanParagraph": "soon available",
    "LDEvent.box1Paragraph": "available soon",
    "LDEvent.box2TrackTitle": "Courses",
    "LDEvent.box2Track1": "A",
    "LDEvent.box2Track2": "B",
    "LDEvent.box2Track3": "C",
    "LDEvent.box2CategoriesTitle": "Classes",
    "LDEvent.box2Categories1": "to be defined",
    "LDEvent.box2Categories2": "to be defined",
    "LDEvent.box2Categories3": "to be defined",
    "LDEvent.box2DistanceTitle": "Length (km)",
    "LDEvent.box2Distance1": "to be defined",
    "LDEvent.box2Distance2": "to be defined",
    "LDEvent.box2Distance3": "to be defined",
    "LDEvent.box2HeightDifferenceTitle": "Climb (m)",
    "LDEvent.box2HeightDifference1": "to be defined",
    "LDEvent.box2HeightDifference2": "to be defined",
    "LDEvent.box2HeightDifference3": "to be defined",
    "LDEvent.box2ControlTitle": "Controls",
    "LDEvent.box2Control1": "to be defined",
    "LDEvent.box2Control2": "to be defined",
    "LDEvent.box2Control3": "to be defined",
    "LDEvent.box2WinningTimeTitle": "Winning time",
    "LDEvent.box2WinningTime1": "to be defined",
    "LDEvent.box2WinningTime2": "to be defined",
    "LDEvent.box2WinningTime3": "to be defined",
    "LDEvent.box2Title": "Track details",
    "LDEvent.box2Paragraph": "available soon",
    "LDEvent.box3Title": "Prices",
    "LDEvent.box3Paragraph11": "FFCO subscribers : ",
    "LDEvent.box3Paragraph12":
      "14 years old and less : 6.97€, 15-18 years old : 10.21€, 18 years old and more : 13.41€",
    "LDEvent.box3Paragraph21": "non-FFCO subscribers : ",
    "LDEvent.box3Paragraph22":
      "Competition pass : 15.00€ ,discovery pass : 12.00€, family pass : 15.00€",
    "LDEvent.box3Paragraph31": "SI rental : ",
    "LDEvent.box3Paragraph32": "3€",
    "LDEvent.box4Title": "Map extracts",
    "LDEvent.box4Paragraph": "available soon",
    "Accomodation.title": "Accomodation",
    "Accomodation.box1Title": "Private rentals",
    "Accomodation.box11Paragraph":
      "Here are a lot of renting possibilities around Fontainebleau and the south of Seine et Marne.",
    "Accomodation.box12Paragraph":
      "This area is well known for climbing and hiking, it is recomended to book an accomodation as soon as possible",
    "Accomodation.box13Paragraph":
      "Here are some web sites with some accomodation available in the area:",
    "Accomodation.box131Paragraph": "(near Nemours)",
    "Accomodation.box14Paragraph":
      "Here are some general web sites for a broader search",
    "Accomodation.box2Title": "Campsites",
    "Accomodation.box2Paragraph":
      "There are several campsites around the forest of Fontainbleau. Here is a list of some of them:",
    "Accomodation.box21Paragraph": "(near Montigny-sur-loing)",
    "Accomodation.box22Paragraph": "(near Noisy-sur-École)",
    "Accomodation.box23Paragraph": "(near Malesherbes)",
    "Accomodation.box24Paragraph": "(near Veneux-les-Sablons)",
    "Accomodation.box3Title": "Tourism office",
    "Accomodation.paragraph":
      "For all the accomodation you can vist tourism office web sites of Fontainebleau, Melun and Nemours",
    "Accomodation.officeFontaineblau": "Tourism office of Fontainebleau",
    "Accomodation.officeMelun": "Tourism office of Melun",
    "Accomodation.officeNemours": "Tourism office of Nemours",
    "Home.title": "Home",
    "Home.bacgroundParagraph":
      "3 orienteering days in the forest of Fontainebleau and its surroundings",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21st",
    "Home.baliseSpParagraph2": "august",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22nd",
    "Home.baliseMdParagraph2": "august",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23rd",
    "Home.baliseLdParagraph2": "august",
    "Home.box1Title": "Informations",
    "Home.box11Paragraph":
      "Orienteering nationales North West 2020 will take place from 21st to 23rd august 2020 in the forest of Fontainebleau. This week end regroup three races:",
    "Home.box121Paragraph":
      "- An urban sprint on friday 21st august afternoon in Chateau Landon",
    "Home.box122Paragraph":
      "- A middle distance on saterday 22nd august afternoon on the map 'Salamandre'",
    "Home.box123Paragraph":
      "- A long distance on sunday 23rd august morning on the map 'Franchard'",
    "Home.box13Paragraph":
      "The terrain for the urban sprint is a small vilage typical form south Seine et Marne with small alleys and residential areas allowing higher speed. There is also several parks that will demand the runners to adapt to all environments.",
    "Home.box14Paragraph":
      "The terrain for the middle and long distance are similar. They are typical of Fontainbleau's forest. On the map there is a lot of rock mass, most often they are on the flank and a lot of sandy hills makes orienteering diffcicult. Between these detailed areas, the visibility is better and a network of path will allow an easier navigation.",
    "Home.box15ParagraphTitle": "Nursery: ",
    "Home.box15Paragraph":
      "Due to COVID-19, we won't be able to set up a nursery during the 3 days, for those with children please specify on the registration that you need different start time.",
    "Home.box16ParagraphTitle": "Refreshment bar: ",
    "Home.box16Paragraph":
      "During the 3 days of event, you will be able to pay with your credit card to the refreshment bar as well as the remaining registration fee and deposit/rent for sportident.",
    "Home.box17ParagraphTitle": "Registration: ",
    "Home.box171Paragraph":
      "Registration for races are now open on the following website",
    "Home.box172Paragraph": "until 7th augustt.",
    "Home.box2Title": "Forbidden area",
    "Home.box2Paragraph":
      "The forbidden area are the ones inside the red border",
    "Home.box3Title": "Official book",
    "Home.box3Paragraph": "available soon",
    "Home.box5Title": "Map extracts",
    "Home.box5Paragraph": "available soon",
    "Home.box6Title": "Terrain Pictures",
    "Home.box6Paragraph": "More pictures",
    "StartList.title": "Start list",
    "StartList.spTitle": "Sprint start list",
    "StartList.spParagraph": "not yet available",
    "StartList.mdTitle": "Middle distance start list",
    "StartList.mdParagraph": "not yet available",
    "StartList.ldTitle": "Long distance start list",
    "StartList.ldParagraph": "not yet available",
    "Partners.title": "Partners",
    "Partners.idf": "Île de France region",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Results",
    "Results.spTitle": "Sprint results",
    "Results.spParagraph": "not yet available",
    "Results.mdTitle": "Middle distance results",
    "Results.mdParagraph": "not yet available",
    "Results.ldTitle": "Long distance results",
    "Results.ldParagraph": "not yet available"
  },
  fr: {
    "Partners.lastUpate": `Dernière mise à jour : ${lastUpate.PARTNERS}`,
    "Results.lastUpate": `Dernière mise à jour : ${lastUpate.RESULTS}`,
    "StartList.lastUpate": `Dernière mise à jour : ${lastUpate.STARTLIST}`,
    "Training.lastUpate": `Dernière mise à jour : ${lastUpate.TRAINING}`,
    "SprintEvent.lastUpate": `Dernière mise à jour : ${lastUpate.SPRINTEVENT}`,
    "MDEvent.lastUpate": `Dernière mise à jour : ${lastUpate.MDEVENT}`,
    "LDEvent.lastUpate": `Dernière mise à jour : ${lastUpate.LDEVENT}`,
    "Accomodation.lastUpate": `Dernière mise à jour : ${lastUpate.ACCOMODATION}`,
    "Gallery.lastUpate": `Dernière mise à jour : ${lastUpate.GALLERY}`,
    "Contact.lastUpate": `Dernière mise à jour : ${lastUpate.CONTACT}`,
    "Home.lastUpate": `Dernière mise à jour : ${lastUpate.HOME}`,
    "LandingPage.Title": "Information importante",
    "LandingPage.paragraph1":
      "Les compétitions prévues du 21 au 23 août sont pour l'instant maintenues en attente des nouvelles mesures gouvernementales. Les équipes sont mobilisées pour que tout se passe bien, les traceurs finalisent leurs circuits. Les inscriptions seront ouvertes à la fin du mois de juin. Nous vous attendons nombreux. A bientôt.",
    "LandingPage.paragraph2": "Le directeur de course",
    "LandingPage.button": "Accéder au site",
    "Gallery.title": "Galerie photos",
    "Gallery.urban": "Sprint Urbain",
    "Gallery.forest": "Course forestière",
    "Footer.copyright": "Tous droits réservés.",
    "Header.headerTitle": "Nationales Nord Ouest 2020",
    "Header.headerTitleShort": "Nationales N-O 2020",
    "Menu.home": "Accueil",
    "Menu.eventTraining": "Entrainements",
    "Menu.eventSprint": "Sprint",
    "Menu.eventMD": "Moyenne Distance",
    "Menu.eventLD": "Longue Distance",
    "Menu.registration": "Inscriptions",
    "Menu.startList": "Listes de départ",
    "Menu.results": "Résultats",
    "Menu.gallery": "Galerie photos",
    "Menu.accommodation": "Hébergements",
    "Menu.partners": "Partenaires",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph":
      "Pour toutes questions sur les Nationales Nord Ouest 2020 vous pouvez nous joindre au mail ci-dessous:",
    "Training.bacgroundParagraph1": "Entrainements",
    "Training.bacgroundParagraph2": "19-20 août 2020",
    "Training.title": "Entrainements",
    "Training.box0Title1": "Informations",
    "Training.box01Paragraph1":
      "Les clubs Balise 77 et OPA Montigny vous proposent deux journées d'entrainement le mercredi 19 et le jeudi 20 août 2020 de 13h à 18H.",
    "Training.box01Paragraph2":
      "Un réseau de postes d'environ 30 balises de niveau noir à vert avec des balisettes sera posé sur les cartes de Larchant et de Bourron Marlotte. Les cartes seront à récupérer à l'Ermitage de Franchard (arena de la MD et de la LD) le mercredi et le jeudi pendant les horaires d'entrainement.",
    "Training.box0Title2": "Tarifs",
    "Training.box02Paragraph1":
      'Le prix d\'un entrainement est de 4 euros. Pour payer, vous pouvez faire un virement, IBAN : FR76 1010 7003 2700 1190 4923 683 BIC : BREDFRPPXXX ou envoyer un chèque à CDCO77 chez Celine Dalier 26 Hameau de Bessonville 77760 La Chapelle La Reine  en identiquant en référence "Entrainements".',
    "Training.box01Paragraph3":
      "Pour reserver vos cartes avant le 7 aout , voici le",
    "Training.box01Paragraph4": "lien",
    "Training.training1Title": "Entrainement 1",
    "Training.training1Box1Title": "Informations pratiques",
    "Training.training1Box1DateTitle": "Date: ",
    "Training.training1Box1DateParagraph": "19-20 août 2020",
    "Training.training1Box1PlacesTitle": "Lieu: ",
    "Training.training1Box1PlacesParagraph": "Forêt de Fontainebleau",
    "Training.training1Box1MapTitle": "Carte: ",
    "Training.training1Box1MapParagraph": "Larchant",
    "Training.training1Box1PlanTitle": "Plan: ",
    "Training.training1Box1PlanParagraph1": "Parking: ",
    "Training.training1Box1PlanParagraph2": "lien google",
    "Training.training1Box4Title": "Extraits de cartes",
    "Training.training1Box4Paragraph": "Bientôt disponible",
    "Training.training2Title": "Entrainement 2",
    "Training.training2Box1Title": "Informations pratiques",
    "Training.training2Box1DateTitle": "Date: ",
    "Training.training2Box1DateParagraph": "19-20 août 2020",
    "Training.training2Box1PlacesTitle": "Lieu: ",
    "Training.training2Box1PlacesParagraph": "Forêt de Fontainebleau",
    "Training.training2Box1MapTitle": "Carte: ",
    "Training.training2Box1MapParagraph": "Grotte Beatrix",
    "Training.training2Box1PlanTitle": "Plan: ",
    "Training.training1Box2PlanParagraph1": "Parking: ",
    "Training.training1Box2PlanParagraph2":
      'Le long de la route "Grande Valée"',
    "Training.training2Box4Title": "Extraits de cartes",
    "Training.training2Box4Paragraph": "Bientôt disponible",
    "SprintEvent.bacgroundParagraph": "Sprint Urbain 21 août 2020",
    "SprintEvent.title": "Sprint",
    "SprintEvent.box1Title": "Informations pratiques",
    "SprintEvent.box1DateTitle": "Date: ",
    "SprintEvent.box1DateParagraph": "21 août 2020",
    "SprintEvent.box1StartListTitle": "Liste de Départ: ",
    "SprintEvent.box1StartListParagraph": "bientôt disponible",
    "SprintEvent.box1ResultTitle": "Résultat: ",
    "SprintEvent.box1ResultParagraph": "pas encore disponible",
    "SprintEvent.box1ParkHomeDistanceTitle": "Distance Parking-Accueil: ",
    "SprintEvent.box1ParkHomeDistanceParagraph": "de 100m à 500m",
    "SprintEvent.box1HomeStartDistanceTitle": "Distance Accueil-Départ: ",
    "SprintEvent.box1HomeStartDistanceParagraph": "800m",
    "SprintEvent.box1OfficialBookTitle": "Livret Officel: ",
    "SprintEvent.box1OfficialBookParagraph": "bientôt disponible",
    "SprintEvent.box1RaceAnnouncementTitle": "Annonce de course: ",
    "SprintEvent.box1RaceAnnouncementParagraph": "Téléchargez ici",
    "SprintEvent.box1TrackDirectorTitle": "Directeur de course: ",
    "SprintEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "SprintEvent.box1PlacesTitle": "Lieu: ",
    "SprintEvent.box1PlacesParagraph": "Chateau Landon",
    "SprintEvent.box1MapTitle": "Carte: ",
    "SprintEvent.box1MapParagraph": "Chateau Landon",
    "SprintEvent.box1PlanTitle": "Plan: ",
    "SprintEvent.box1PlanParagraph": "bientôt disponible",
    "SprintEvent.box1Paragraph": "Bientôt disponible",
    "SprintEvent.box2TrackTitle": "Circuit",
    "SprintEvent.box2Track1": "A",
    "SprintEvent.box2Track2": "B",
    "SprintEvent.box2Track3": "C",
    "SprintEvent.box2CategoriesTitle": "Catégories",
    "SprintEvent.box2Categories1": "à définir",
    "SprintEvent.box2Categories2": "à définir",
    "SprintEvent.box2Categories3": "à définir",
    "SprintEvent.box2DistanceTitle": "Distance",
    "SprintEvent.box2Distance1": "à définir",
    "SprintEvent.box2Distance2": "à définir",
    "SprintEvent.box2Distance3": "à définir",
    "SprintEvent.box2HeightDifferenceTitle": "Dénivelé",
    "SprintEvent.box2HeightDifference1": "à définir",
    "SprintEvent.box2HeightDifference2": "à définir",
    "SprintEvent.box2HeightDifference3": "à définir",
    "SprintEvent.box2ControlTitle": "Postes",
    "SprintEvent.box2Control1": "à définir",
    "SprintEvent.box2Control2": "à définir",
    "SprintEvent.box2Control3": "à définir",
    "SprintEvent.box2WinningTimeTitle": "Temps du vainqueur",
    "SprintEvent.box2WinningTime1": "à définir",
    "SprintEvent.box2WinningTime2": "à définir",
    "SprintEvent.box2WinningTime3": "à définir",
    "SprintEvent.box2Title": "Détails des circuits",
    "SprintEvent.box2Paragraph": "Bientôt disponible",
    "SprintEvent.box3Title": "Tarifs",
    "SprintEvent.box3Paragraph11": "Licenciés FFCO : ",
    "SprintEvent.box3Paragraph12":
      "moins de 18 ans : 5,00€, 18 ans et plus : 6,00€",
    "SprintEvent.box3Paragraph21": "Non-licenciés FFCO : ",
    "SprintEvent.box3Paragraph22":
      "Pass-compétition : 12,00€ ,Pass-découverte : 8,00€, Pass-famille : 12,00€",
    "SprintEvent.box3Paragraph31": "Location de puce : ",
    "SprintEvent.box3Paragraph32": "3€",
    "SprintEvent.box4Title": "Extraits de cartes",
    "SprintEvent.box4Paragraph1": "bientôt disponible",
    "MDEvent.bacgroundParagraph": "Moyenne distance 22 août 2020",
    "MDEvent.title": "Moyenne Distance",
    "MDEvent.box1Title": "Informations pratiques",
    "MDEvent.box1DateTitle": "Date: ",
    "MDEvent.box1DateParagraph": "22 août 2020",
    "MDEvent.box1StartListTitle": "Liste de Départ: ",
    "MDEvent.box1StartListParagraph": "bientôt disponible",
    "MDEvent.box1ResultTitle": "Résultat: ",
    "MDEvent.box1ResultParagraph": "pas encore disponible",
    "MDEvent.box1ParkHomeDistanceTitle": "Distance Parking-Accueil: ",
    "MDEvent.box1ParkHomeDistanceParagraph": "de 200 m à 1000m ",
    "MDEvent.box1HomeStartDistanceTitle": "Distance Accueil-Départ: ",
    "MDEvent.box1HomeStartDistanceParagraph": "600m",
    "MDEvent.box1OfficialBookTitle": "Livret Officel: ",
    "MDEvent.box1OfficialBookParagraph": "bientôt disponible",
    "MDEvent.box1RaceAnnouncementTitle": "Annonce de course: ",
    "MDEvent.box1RaceAnnouncementParagraph": "Téléchargez ici",
    "MDEvent.box1TrackDirectorTitle": "Directeur de course: ",
    "MDEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "MDEvent.box1PlacesTitle": "Lieu: ",
    "MDEvent.box1PlacesParagraph": "Forêt de Fontainebleau",
    "MDEvent.box1MapTitle": "Carte: ",
    "MDEvent.box1MapParagraph": "Salamandre",
    "MDEvent.box1PlanTitle": "Plan: ",
    "MDEvent.box1PlanParagraph": "bientôt disponible",
    "MDEvent.box1Paragraph": "Bientôt disponible",
    "MDEvent.box2TrackTitle": "Circuit",
    "MDEvent.box2Track1": "A",
    "MDEvent.box2Track2": "B",
    "MDEvent.box2Track3": "C",
    "MDEvent.box2CategoriesTitle": "Catégories",
    "MDEvent.box2Categories1": "à définir",
    "MDEvent.box2Categories2": "à définir",
    "MDEvent.box2Categories3": "à définir",
    "MDEvent.box2DistanceTitle": "Distance",
    "MDEvent.box2Distance1": "à définir",
    "MDEvent.box2Distance2": "à définir",
    "MDEvent.box2Distance3": "à définir",
    "MDEvent.box2HeightDifferenceTitle": "Dénivelé",
    "MDEvent.box2HeightDifference1": "à définir",
    "MDEvent.box2HeightDifference2": "à définir",
    "MDEvent.box2HeightDifference3": "à définir",
    "MDEvent.box2ControlTitle": "Postes",
    "MDEvent.box2Control1": "à définir",
    "MDEvent.box2Control2": "à définir",
    "MDEvent.box2Control3": "à définir",
    "MDEvent.box2WinningTimeTitle": "Temps du vainqueur",
    "MDEvent.box2WinningTime1": "à définir",
    "MDEvent.box2WinningTime2": "à définir",
    "MDEvent.box2WinningTime3": "à définir",
    "MDEvent.box2Title": "Détails des circuits",
    "MDEvent.box2Paragraph": "Bientôt disponible",
    "MDEvent.box3Title": "Tarifs",
    "MDEvent.box3Paragraph11": "Licenciés FFCO : ",
    "MDEvent.box3Paragraph12":
      "14ans et moins : 6,97€, 15-18 ans : 10,21€, 19ans et plus : 13,41€",
    "MDEvent.box3Paragraph21": "Non-licenciés FFCO : ",
    "MDEvent.box3Paragraph22":
      "Pass-compétition : 15,00€ ,Pass-découverte : 12,00€, Pass-famille : 15,00€",
    "MDEvent.box3Paragraph31": "Location de puce : ",
    "MDEvent.box3Paragraph32": "3€",
    "MDEvent.box4Title": "Extraits de cartes",
    "MDEvent.box4Paragraph1": "bientôt disponible",
    "LDEvent.bacgroundParagraph": "Longue distance 23 août 2020",
    "LDEvent.title": "Longue Distance",
    "LDEvent.box1Title": "Informations pratiques",
    "LDEvent.box1DateTitle": "Date: ",
    "LDEvent.box1DateParagraph": "23 août 2020",
    "LDEvent.box1StartListTitle": "Liste de Départ: ",
    "LDEvent.box1StartListParagraph": "bientôt disponible",
    "LDEvent.box1ResultTitle": "Résultat: ",
    "LDEvent.box1ResultParagraph": "pas encore disponible",
    "LDEvent.box1ParkHomeDistanceTitle": "Distance Parking-Accueil: ",
    "LDEvent.box1ParkHomeDistanceParagraph": "de 200m à 1000m",
    "LDEvent.box1HomeStartDistanceTitle": "Distance Accueil-Départ: ",
    "LDEvent.box1HomeStartDistanceParagraph": "500m",
    "LDEvent.box1OfficialBookTitle": "Livret Officel: ",
    "LDEvent.box1OfficialBookParagraph": "bientôt disponible",
    "LDEvent.box1RaceAnnouncementTitle": "Annonce de course: ",
    "LDEvent.box1RaceAnnouncementParagraph": "Téléchargez ici",
    "LDEvent.box1TrackDirectorTitle": "Directeur de course: ",
    "LDEvent.box1TrackDirectorParagraph": "Alain Guillon",
    "LDEvent.box1PlacesTitle": "Lieu: ",
    "LDEvent.box1PlacesParagraph": "Forêt de Fontainebleau",
    "LDEvent.box1MapTitle": "Carte: ",
    "LDEvent.box1MapParagraph": "Franchard",
    "LDEvent.box1PlanTitle": "Plan: ",
    "LDEvent.box1PlanParagraph": "bientôt disponible",
    "LDEvent.box1Paragraph": "Bientôt disponible",
    "LDEvent.box2TrackTitle": "Circuit",
    "LDEvent.box2Track1": "A",
    "LDEvent.box2Track2": "B",
    "LDEvent.box2Track3": "C",
    "LDEvent.box2CategoriesTitle": "Catégories",
    "LDEvent.box2Categories1": "à définir",
    "LDEvent.box2Categories2": "à définir",
    "LDEvent.box2Categories3": "à définir",
    "LDEvent.box2DistanceTitle": "Distance",
    "LDEvent.box2Distance1": "à définir",
    "LDEvent.box2Distance2": "à définir",
    "LDEvent.box2Distance3": "à définir",
    "LDEvent.box2HeightDifferenceTitle": "Dénivelé",
    "LDEvent.box2HeightDifference1": "à définir",
    "LDEvent.box2HeightDifference2": "à définir",
    "LDEvent.box2HeightDifference3": "à définir",
    "LDEvent.box2ControlTitle": "Postes",
    "LDEvent.box2Control1": "à définir",
    "LDEvent.box2Control2": "à définir",
    "LDEvent.box2Control3": "à définir",
    "LDEvent.box2WinningTimeTitle": "Temps du vainqueur",
    "LDEvent.box2WinningTime1": "à définir",
    "LDEvent.box2WinningTime2": "à définir",
    "LDEvent.box2WinningTime3": "à définir",
    "LDEvent.box2Title": "Détails des circuits",
    "LDEvent.box2Paragraph": "Bientôt disponible",
    "LDEvent.box3Title": "Tarifs",
    "LDEvent.box3Paragraph11": "Licenciés FFCO : ",
    "LDEvent.box3Paragraph12":
      "14ans et moins : 6,97€, 15-18 ans : 10,21€, 19ans et plus : 13,41€",
    "LDEvent.box3Paragraph21": "Non-licenciés FFCO : ",
    "LDEvent.box3Paragraph22":
      "Pass-compétition : 15,00€ ,Pass-découverte : 12,00€, Pass-famille : 15,00€",
    "LDEvent.box3Paragraph31": "Location de puce : ",
    "LDEvent.box3Paragraph32": "3€",
    "LDEvent.box4Title": "Extraits de cartes",
    "LDEvent.box4Paragraph": "Bientôt disponible",
    "Accomodation.title": "Hébergements",
    "Accomodation.box1Title": "Locations",
    "Accomodation.box11Paragraph":
      "Il y a de nombreuses possibilités de location d’hébergement de type gîte aux alentours de Fontainebleau et dans le sud de la Seine et Marne.",
    "Accomodation.box12Paragraph":
      "La region est prisée des grimpeurs et randonneurs, il est donc conseillé de réserver un hébergement le plus tôt possible pour être sûr d’avoir de la place.",
    "Accomodation.box13Paragraph":
      "Voici quelques sites web recensant des hébergements disponibles dans la region:",
    "Accomodation.box131Paragraph": "(Près de Nemours)",
    "Accomodation.box14Paragraph":
      "Voici quelques sites web généraux pour une recherche plus vaste:",
    "Accomodation.box2Title": "Campings",
    "Accomodation.box2Paragraph":
      "Il y a plusieurs campings autour de la forêt de fontainebleau. Voici une liste non exhaustive des campings les plus populaires:",
    "Accomodation.box21Paragraph": "(près de Montigny-sur-loing)",
    "Accomodation.box22Paragraph": "(près de Noisy-sur-École)",
    "Accomodation.box23Paragraph": "(près de Malesherbes)",
    "Accomodation.box24Paragraph": "(près de Veneux-les-Sablons)",
    "Accomodation.box3Title": "Office de tourisme",
    "Accomodation.paragraph":
      "Vous pouvez aussi consulter les sites des offices de tourisme de Fontainebleau, Melun et Nemours pour plus de renseignements sur les hébergements dans la région",
    "Accomodation.officeFontaineblau": "Office de tourisme de Fontainebleau",
    "Accomodation.officeMelun": "Office de tourisme de Melun",
    "Accomodation.officeNemours": "Office de tourisme de Nemours",
    "Home.title": "Accueil",
    "Home.bacgroundParagraph":
      "3 jours de course d'orientation en forêt de Fontainebleau et ses environs",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21",
    "Home.baliseSpParagraph2": "août",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22",
    "Home.baliseMdParagraph2": "août",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23",
    "Home.baliseLdParagraph2": "août",
    "Home.box1Title": "Informations",
    "Home.box11Paragraph":
      "Les Nationales Nord Ouest 2020 de course d’orientation auront lieu du 21 au 23 août 2020 dans la forêt de Fontainebleau. Ce long week-end regroupe trois courses comptant pour le classement national:",
    "Home.box121Paragraph":
      "- Un Sprint Urbain le vendredi 21 août après midi dans la ville de Chateau Landon",
    "Home.box122Paragraph":
      "- Une Moyenne Distance le samedi 22 août après midi sur la carte de la Salamandre",
    "Home.box123Paragraph":
      "- Une Longue Distance le dimache 23 août matin sur la carte de Franchard",
    "Home.box13Paragraph":
      "Le terrain du sprint urbain est un petit village typique du sud de la Seine et Marne avec quelques petites ruelles ainsi que des quartiers résidentiels offrant une vitesse de course plus élevée. La carte possède également plusieurs parcs ou prés qui nécessiteront aux coureurs de s’adapter aux différents environnements.",
    "Home.box14Paragraph":
      "Les terrains de la moyenne distance et de la longue distance sont similaires et typiques des terrains de la forêt de fontainebleau. La carte possède de nombreux chaos rocheux le plus souvent sur les flancs et des nombreuses collines sableuses qui rendent l’orientation difficile. Entre ces zones détaillées, la visibilité est bien meilleure et un réseau de chemin assez dense devrait permettre une navigation plus aisée.",
    "Home.box15ParagraphTitle": "Garderie: ",
    "Home.box15Paragraph":
      "Face au COVID-19, nous ne sommes pas en mesure de mettre en place une garderie sur les 3 jours, merci pour ceux qui ont des enfants, de préciser lors des inscriptions d'avoir des heures de départ décalées.",
    "Home.box16ParagraphTitle": "Buvette: ",
    "Home.box16Paragraph":
      "Lors des 3 jours , vous aurez la possibilité de payer à la buvette en carte bleue ainsi que les droits d'inscription restants et la location et la caution pour les sportident.",
    "Home.box17ParagraphTitle": "Inscriptions: ",
    "Home.box171Paragraph":
      "Les inscriptions aux 3 courses sont ouvertes sur le site de la",
    "Home.box172Paragraph": "jusqu'au 7 aout.",
    "Home.box2Title": "Zones gelées",
    "Home.box2Paragraph": "Les zones gelées sont délimitées par la ligne rouge",
    "Home.box3Title": "Livret d'accueil",
    "Home.box3Paragraph": "bientôt disponible",
    "Home.box5Title": "Extraits de cartes",
    "Home.box5Paragraph": "bientôt disponible",
    "Home.box6Title": "Photos du terrain",
    "Home.box6Paragraph": "Plus de photos",
    "StartList.title": "Listes de départ",
    "StartList.spTitle": "Liste de départ du Sprint",
    "StartList.spParagraph": "Pas encore disponible",
    "StartList.mdTitle": "Liste de départ de la MD",
    "StartList.mdParagraph": "Pas encore disponible",
    "StartList.ldTitle": "Liste de départ de la LD",
    "StartList.ldParagraph": "Pas encore disponible",
    "Partners.title": "Partenaires",
    "Partners.idf": "Région Île de France",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Résultats",
    "Results.spTitle": "Résultats du Sprint",
    "Results.spParagraph": "Pas encore disponible",
    "Results.mdTitle": "Résultats de la MD",
    "Results.mdParagraph": "Pas encore disponible",
    "Results.ldTitle": "Résultats de la LD",
    "Results.ldParagraph": "Pas encore disponible"
  }
};

export default language;
