const language = {
  en: {
    "Gallery.title": "Pictures gallery",
    "Footer.copyright": "All right reserved.",
    "Header.headerTitle": "Nationales North West 2020",
    "Header.headerTitleShort": "Nationales N-W 2020",
    "Menu.home": "Home",
    "Menu.events": "Races",
    "Menu.registration": "Entries",
    "Menu.startList": "Start list",
    "Menu.results": "Results",
    "Menu.gallery": "Pictures gallery",
    "Menu.accommodation": "Accomodation",
    "Menu.partners": "Partners",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph": "If you have any question, please contact the person below:",
    "Event.title": "Races",
    "Event.paragraph1": "Event composed by 3 races:",
    "Event.paragraph2": "21st august: urban sprint",
    "Event.paragraph3": "22nd august: middle distance",
    "Event.paragraph4": "23rd august: long distance",
    "Event.event1Title": "Sprint",
    "Event.event1Paragrpah": "The sprint will take place the 21st august",
    "Event.event2Title": "MD",
    "Event.event2Paragrpah": "The middle distance will take place the 22nd august",
    "Event.event3Title": "LD",
    "Event.event3Paragrpah": "The long distance will take place the 23rd august",
    "Accomodation.title": "Accomodation",
    "Accomodation.paragraph": "For all the accomodation you can check tourism office web sites of Fontainebleau, Melun and Nemours",
    "Accomodation.officeFontaineblau": "Tourism office of Fontainebleau",
    "Accomodation.officeMelun": "Tourism office of Melun",
    "Accomodation.officeNemours": "Tourism office of Nemours",
    "Home.title": "Home",
    "Home.bacgroundParagraph": "3 orienteering days in the forest of Fontainebleau and its surroundings",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21st",
    "Home.baliseSpParagraph2": "august",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22nd",
    "Home.baliseMdParagraph2": "august",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23rd",
    "Home.baliseLdParagraph2": "august",
    "Home.box1Title": "Terrain",
    "Home.box1Paragraph": "awailable soon",
    "Home.box2Title": "Forbidden area",
    "Home.box2Paragraph": "The forbidden area are the ones inside the red border",
    "Home.box3Title": "Official book",
    "Home.box3Paragraph": "awailable soon",
    "Home.box4Title": "Information",
    "Home.box4Paragraph": "flyer",
    "Registration.title": "Entries",
    "Registration.paragraph": "The entries will take place on the website of the federation",
    "StartList.title": "Start list",
    "StartList.spTitle": "Sprint start list",
    "StartList.spParagraph": "not yet awailable",
    "StartList.mdTitle": "Middle distance start list",
    "StartList.mdParagraph": "not yet awailablee",
    "StartList.ldTitle": "Long distance start list",
    "StartList.ldParagraph": "not yet awailablee",
    "Partners.title": "Partners",
    "Partners.idf": "Île de France region",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Results",
    "Results.spTitle": "Sprint results",
    "Results.spParagraph": "not yet awailable",
    "Results.mdTitle": "Middle distance results",
    "Results.mdParagraph": "not yet awailable",
    "Results.ldTitle": "Long distance results",
    "Results.ldParagraph": "not yet awailable"
  },
  fr: {
    "Gallery.title": "Galerie photos",
    "Footer.copyright": "Tous droits réservés.",
    "Header.headerTitle": "Nationales Nord Ouest 2020",
    "Header.headerTitleShort": "Nationales N-O 2020",
    "Menu.home": "Accueil",
    "Menu.events": "Compétitions",
    "Menu.registration": "Inscriptions",
    "Menu.startList": "Listes de départ",
    "Menu.results": "Résultats",
    "Menu.gallery": "Galerie photos",
    "Menu.accommodation": "Hébergements",
    "Menu.partners": "Partenaires",
    "Menu.contact": "Contacts",
    "Contact.title": "Contacts",
    "Contact.paragraph": "Pour toutes questions sur la Nationale Nord Ouest 2020 vous pouvez nous joindre à ces différents contacts",
    "Event.title": "Compétitions",
    "Event.paragraph1": "Évenement composé de 3 courses:",
    "Event.paragraph2": "Le 21 août: Un sprint urbain",
    "Event.paragraph3": "Le 22 août: Une moyenne distance",
    "Event.paragraph4": "Le 23 août: La Nationale, une longue distance",
    "Event.event1Title": "Sprint",
    "Event.event1Paragrpah": "Le sprint aura lieu le 21 août",
    "Event.event2Title": "MD",
    "Event.event2Paragrpah": "La MD aura lieu le 22 août",
    "Event.event3Title": "LD",
    "Event.event3Paragrpah": "La LD aura lieu le 23 août",
    "Accomodation.title": "Hébergements",
    "Accomodation.paragraph": "Pour les hébergements vous pouvez consultez les sites des offices de tourisme de Fontainebleau, Melun et Nemours",
    "Accomodation.officeFontaineblau": "Office de tourisme de Fontainebleau",
    "Accomodation.officeMelun": "Office de tourisme de Melun",
    "Accomodation.officeNemours": "Office de tourisme de Nemours",
    "Home.title": "Accueil",
    "Home.bacgroundParagraph": "3 jours de course d'orientation en forêt de Fontainebleau et ses environs",
    "Home.baliseSpTitle": "Sprint",
    "Home.baliseSpParagraph1": "21",
    "Home.baliseSpParagraph2": "août",
    "Home.baliseMdTitle": "MD",
    "Home.baliseMdParagraph1": "22",
    "Home.baliseMdParagraph2": "août",
    "Home.baliseLdTitle": "LD",
    "Home.baliseLdParagraph1": "23",
    "Home.baliseLdParagraph2": "août",
    "Home.box1Title": "Terrain",
    "Home.box1Paragraph": "bientôt disponible",
    "Home.box2Title": "Zone gelée",
    "Home.box2Paragraph": "Les zones gelée sont celles à l'intérieur de la ligne rouge",
    "Home.box3Title": "Livret d'accueil",
    "Home.box3Paragraph": "bientôt disponible",
    "Home.box4Title": "Annonces",
    "Home.box4Paragraph": "flyer",
    "Registration.title": "Inscriptions",
    "Registration.paragraph": "Les inscriptions vont être réalisées par le biais du site de la",
    "StartList.title": "Listes de départ",
    "StartList.spTitle": "Liste de départ du Sprint",
    "StartList.spParagraph": "Pas encore disponible",
    "StartList.mdTitle": "Liste de départ de la MD",
    "StartList.mdParagraph": "Pas encore disponible",
    "StartList.ldTitle": "Liste de départ de la LD",
    "StartList.ldParagraph": "Pas encore disponible",
    "Partners.title": "Partenaires",
    "Partners.idf": "Région Île de France",
    "Partners.lifco": "Ligue île de France",
    "Results.title": "Résultats",
    "Results.spTitle": "Résultats du Sprint",
    "Results.spParagraph": "Pas encore disponible",
    "Results.mdTitle": "Résultats de la MD",
    "Results.mdParagraph": "Pas encore disponible",
    "Results.ldTitle": "Résultats de la LD",
    "Results.ldParagraph": "Pas encore disponible"
  }
};

export default language;
